name: sales_tracker
description: A simple Sales Tracker mobile app (Flutter) — amounts in Ksh.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.8
  path_provider: ^2.0.15
  path: ^1.8.4
  intl: ^0.18.1
  pdf: ^3.10.1
  printing: ^5.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
